### ISSUE TITLE
이렇게 복잡한게...

### ISSUE THREAD

**Issue by kohyuk91** [lazypic/maya-install-centos7#1]
이렇게 복잡한게 10~20개의 문서로 잘게 쪼개져있으니 ㅠ
무슨 보물찾기도 아니고 흑흑

**Comment by kybin** [comment]
블렌더 씁시다 ㅋㅋ

**Comment by kohyuk91** [comment]
기승전블렌더 ㅋㅋ
오픈소스는 사랑입니다 ㅋㅋ

**Comment by kohyuk91** [comment]
뻘짓하고 있었네요...
마야2019 시리얼키 받아놓고
마야2018을 설치해서 자꾸 오류가 발생하고 있었네요 ㅋㅋ

여기 가이드 따라하면 CentOS 7.6에서 마야 2019 설치할수 있습니다!

**Comment by khw7096** [comment]
화이팅이예요!!!
